version: '3.7'
services:
  app:
    build: .
    networks:
      - vswitch0
    expose:
      - "80"
    env_file: .env
    environment:
      FLASK_ENV: 'development'
    ports:
      - 80:${FLASK_APP_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_APP_PORT}"]
      interval: 10s
      retries: 5
      start_period: 1s
    volumes:
      - .:${FLASK_APP_PATH}
  db:
    image: "mysql:8.4"
    env_file: .env
    networks:
      - vswitch0
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    restart: unless-stopped
    volumes:
      - .${MYSQL_DATA_DIR}:/var/lib/mysql      
      - .${MYSQL_CONF_DIR}:/etc/mysql/conf.d

networks:
  vswitch0:
    driver: bridge
